### PR TITLE
Use function token colour for async token

### PR DESCRIPTION
**Pull request by sladiri**
image

after

image

### CODE REVIEW

**Comment by gaearon** [comment]
Are you using Sublime Babel JS syntax? Your "before" colors look different than I'd expect (in particular `now()` call should be yellow).

**Comment by sladiri** [comment]
No, but I was already wondering if there is something different in the colours in my setup. I just reinstalled VS Code and also deleted all settings.
I am using Windows 10, in case that would make a difference.

Here is the display after reinstall, default Dark+ theme and no extensions:
image

Here with Subliminal:
image

**Comment by sladiri** [comment]
Now I get it, I overlooked the part about Sublime syntax. I will look at my PRs again. :)

**Comment by sladiri** [comment]
This makes no difference with Sublime syntax.

**Pull request closed without merging**
